version: "3.5"
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    volumes:
     - ./certs:/etc/nginx/certs
     - /var/run/docker.sock:/tmp/docker.sock:ro
     - ./conf.d:/etc/nginx/conf.d
     - vhost:/etc/nginx/vhost.d
     - vl_html:/usr/share/nginx/html
    ports:
     - "80:80"
     - "443:443"
    networks:
     - nginx-proxy
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    environment:
      - DEFAULT_HOST=nginx-berserk

  nginx-berserk:
    image: nginx
    volumes:
      - ./berserk/download_content:/usr/share/nginx/html:ro
      - ./berserk/conf.d/default.conf:/etc/nginx/conf.d/default.conf"
    environment:
      - LETSENCRYPT_HOST=${BERSERK_URL}
      - VIRTUAL_HOST=${BERSERK_URL}
      - VIRTUAL_PORT=80
    networks:
      - nginx-proxy

  letsencrypt:
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - vl_html:/usr/share/nginx/html
volumes:
  vhost:
  vl_html:
networks:
  nginx-proxy:
    name: proxy

